services:
  database:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=${WAS_ACCESSORSETTINGS_DBMSDBNAME:-postgres}
      - POSTGRES_USER=${WAS_ACCESSORSETTINGS_DBMSUSER:-postgres}
      - POSTGRES_PASSWORD=${WAS_ACCESSORSETTINGS_DBMSPASSWORD:-defaultpassword}
    ports:
      - "5432:5432"
    restart: unless-stopped

  was_backend:
    build: .
    environment:
      - WAS_ACCESSORSETTINGS_DBMSADDRESS=database
      - WAS_ACCESSORSETTINGS_DBMSPORT=5432
      - WAS_ACCESSORSETTINGS_DBMSDBNAME=${WAS_ACCESSORSETTINGS_DBMSDBNAME:-postgres}
      - WAS_ACCESSORSETTINGS_DBMSUSER=${WAS_ACCESSORSETTINGS_DBMSUSER:-postgres}
      - WAS_ACCESSORSETTINGS_DBMSPASSWORD=${WAS_ACCESSORSETTINGS_DBMSPASSWORD:-defaultpassword}
    ports:
      - "127.0.0.1:10000:10000"
