services:
  database:
    image: postgres:16.4
    environment:
      - POSTGRES_PASSWORD=${RMS_DB_PASSWD:-defaultpassword}
      - POSTGRES_DB=${RMS_DB_NAME:-postgres}
    ports:
      - "5432:5432"
    restart: unless-stopped

  rms_backend:
    build: .
    environment:
      - RMS_DB_ADRESS=postgres://database
      - RMS_DB_PORT=5432
      - RMS_DB_NAME=${RMS_DB_NAME:-postgres}
      - RMS_DB_PASSWD=${RMS_DB_PASSWD:-defaultpassword}
