services:
  database:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=${RMS_ACCESSORSETTINGS_DBMSDBNAME:-postgres}
      - POSTGRES_USER=${RMS_ACCESSORSETTINGS_DBMSUSER:-postgres}
      - POSTGRES_PASSWORD=${RMS_ACCESSORSETTINGS_DBMSPASSWORD:-defaultpassword}
    ports:
      - "5432:5432"
    restart: unless-stopped

  rms_backend:
    build: .
    environment:
      - RMS_ACCESSORSETTINGS_DBMSADDRESS=postgres://database
      - RMS_ACCESSORSETTINGS_DBMSPORT=5432
      - RMS_ACCESSORSETTINGS_DBMSDBNAME=${RMS_ACCESSORSETTINGS_DBMSDBNAME:-postgres}
      - RMS_ACCESSORSETTINGS_DBMSUSER=${RMS_ACCESSORSETTINGS_DBMSUSER:-postgres}
      - RMS_ACCESSORSETTINGS_DBMSPASSWORD=${RMS_ACCESSORSETTINGS_DBMSPASSWORD:-defaultpassword}
